const GameActionTypes = {
  CHANGE_BOARD_SIZE: 'CHANGE_BOARD_SIZE',
  INITIALIZE_BOARD: 'INITIALIZE_BOARD',
  REVEAL_SQUARE: 'REVEAL_SQUARE',
  RESET_BOARD: 'RESET_BOARD',
  TOGGLE_FLAG: 'TOGGLE_FLAG',
};

export default GameActionTypes;
