const GameActionTypes = {
  CHANGE_BOARD_SIZE: 'CHANGE_BOARD_SIZE',
  POPULATE_BOARD: 'POPULATE_BOARD',
  REVEAL_FIELD: 'REVEAL_FIELD',
  TOGGLE_FLAG: 'TOGGLE_FLAG',
  RESET_BOARD: 'RESET_BOARD',
  GAME_OVER: 'GAME_OVER',
};

export default GameActionTypes;
